# Generated by Django 5.1.1 on 2024-10-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('question_text', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('answered', models.BooleanField(default=False)),
            ],
        ),
    ]
